openapi: 3.0.0
info:
  title: Polar H10 API
  description: API for interacting with Polar H10 device
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /connect:
    get:
      operationId: app.connect
      summary: Connect to Polar H10
      responses:
        200:
          description: Connection successful
        404:
          description: Polar device not found
        500:
          description: Error connecting to Polar H10
  /device_info:
    get:
      operationId: app.get_device_info
      summary: Get device information
      responses:
        200:
          description: Device information retrieved successfully
        404:
          description: Polar device not found
        500:
          description: Error getting device information
  /heart_rate:
    get:
      operationId: app.stream_heart_rate
      summary: Get real-time heart rate
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string